/*
  # Insert initial product data

  1. Data Changes
    - Inserts 5 initial flower products into the products table
    - Each product includes:
      - name
      - description
      - price
      - image_url
      - sku (generated from name)
      - category (set to 'flowers')

  Note: SKUs are generated by converting product names to lowercase and replacing spaces with hyphens
*/

INSERT INTO products (name, description, price, sku, image_url, category)
VALUES
  (
    'Red Rose Bouquet',
    'A classic bouquet of fresh red roses, symbolizing love and passion.',
    29.99,
    'red-rose-bouquet',
    'https://images.unsplash.com/photo-1587300003388-59208cc962cb',
    'flowers'
  ),
  (
    'Sunflower Arrangement',
    'Bright and cheerful sunflowers arranged to bring warmth to any room.',
    24.99,
    'sunflower-arrangement',
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
    'flowers'
  ),
  (
    'Pink Tulip Bundle',
    'A delicate bundle of pink tulips, perfect for springtime celebrations.',
    19.99,
    'pink-tulip-bundle',
    'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
    'flowers'
  ),
  (
    'White Lily Bouquet',
    'Elegant white lilies that exude grace and sophistication.',
    34.99,
    'white-lily-bouquet',
    'https://images.unsplash.com/photo-1519066629447-267fffa62d4b',
    'flowers'
  ),
  (
    'Mixed Wildflower Basket',
    'A charming basket filled with a variety of colorful wildflowers.',
    27.99,
    'mixed-wildflower-basket',
    'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
    'flowers'
  );